development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url:  redis://:pddd31ae4129d56689bacfc300dc55dcb6134bbee9f8cf7c4a679e2739a68f2ae@ec2-18-235-208-59.compute-1.amazonaws.com:12109# <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #channel_prefix: message_me_production
